<?php

/**
 * @file
 * Contains todo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function todo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the todo module.
    case 'help.page.todo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Todo list custom module for drupal 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function todo_theme($existing, $type, $theme, $path) {

  return [		
    //Name of the theme hook. This is used in the controller to trigger the hook.
    'todo_theme_hook' => [
      'render element' => 'children',
      //If no template name is defined here, it defaults to the name of the theme hook, ie. module-name-theme-hook.html.twig
      'template' => 'todo-theme-hook',
      //Optionally define path to Twig template files. Defaults to the module's ./templates/ directory.
      'path' => $path . '/templates',
      //Optionally define variables that will be passed to the Twig template and set default values for them.
      'variables' => [
          'variable1' => 'Yet another default text.',
          'variable2' => 0,
          'variable3' => [0, 0, 0],
          'tasklist' => [],
      ],
    ],
  ];

}